# Generated by Django 6.0.3 on 2026-04-20 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='apply_link',
            field=models.URLField(blank=True, help_text='Link to apply for this service'),
        ),
        migrations.AddField(
            model_name='service',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service charges amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='documents_required',
            field=models.TextField(blank=True, help_text='List of required documents'),
        ),
        migrations.AddField(
            model_name='service',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Assign to a specific page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.page'),
        ),
        migrations.AddField(
            model_name='service',
            name='tutorial_link',
            field=models.URLField(blank=True, help_text='YouTube or tutorial video link'),
        ),
    ]
