# Generated by Django 6.0.3 on 2026-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='requests/aadhaar/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='requests/pan/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='requests/photos/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='requests/signatures/'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
