# Generated by Django 6.0.3 on 2026-04-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequest_aadhaar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='requests/address_proof/'),
        ),
    ]
