# Generated by Django 6.0.3 on 2026-04-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicerequest_address_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='requests/completed/'),
        ),
    ]
