# Generated by Django 6.0.3 on 2026-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicerequest_completed_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
