# Generated by Django 6.0.3 on 2026-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='requests/bank_passbook/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='birth_cert',
            field=models.FileField(blank=True, null=True, upload_to='requests/birth_cert/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='community_cert',
            field=models.FileField(blank=True, null=True, upload_to='requests/community_cert/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='degree_cert',
            field=models.FileField(blank=True, null=True, upload_to='requests/degree_cert/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='disability_cert',
            field=models.FileField(blank=True, null=True, upload_to='requests/disability_cert/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='requests/driving_license/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ews_cert',
            field=models.FileField(blank=True, null=True, upload_to='requests/ews_cert/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='experience_cert',
            field=models.FileField(blank=True, null=True, upload_to='requests/experience_cert/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='hospital_records',
            field=models.FileField(blank=True, null=True, upload_to='requests/hospital_records/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='income_cert',
            field=models.FileField(blank=True, null=True, upload_to='requests/income_cert/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='requests/marksheet/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='marriage_cert',
            field=models.FileField(blank=True, null=True, upload_to='requests/marriage_cert/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='requests/passport/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pcc',
            field=models.FileField(blank=True, null=True, upload_to='requests/pcc/'),
        ),
    ]
