# Generated by Django 6.0.3 on 2026-04-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicerequest_bank_passbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='bank_passbook',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='birth_cert',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='community_cert',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='degree_cert',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='disability_cert',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='ews_cert',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='experience_cert',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='hospital_records',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='income_cert',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='marksheet',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='marriage_cert',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='pcc',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='dynamic_documents',
            field=models.JSONField(blank=True, default=dict, help_text='Stores dynamic document uploads as JSON'),
        ),
    ]
