# Generated by Django 6.0.4 on 2026-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_servicerequest_bank_passbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='dynamic_documents',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
