# Generated by Django 6.0.3 on 2026-05-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sender_role',
            field=models.CharField(choices=[('USER', 'User'), ('AGENT1', 'Agent 1'), ('AGENT2', 'Agent 2')], default='USER', max_length=20),
        ),
    ]
