# Generated by Django 6.0.4 on 2026-05-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='minimum_age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum age required to apply for this service'),
        ),
    ]
