# Generated by Django 6.0.3 on 2026-05-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_service_minimum_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='aadhaar_number',
        ),
    ]
